try:
    print("Try Block")
except NameError:
    print("Except Block")
finally:
    print("Finally Block")
